{% set name = "types-aiofiles" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-aiofiles-{{ version }}.tar.gz
  sha256: 5c54783745252302f5ba3e14d8f7e8547d100f72c74c9a5478ce2f7f01aa0cda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/aiofiles-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for aiofiles
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
